drop
view if
exists addotnet.raw_user_events_new;
CREATE VIEW addotnet.raw_user_events_new AS
SELECT CASE
           WHEN length(CAST(epoch as STRING)) = 13 THEN to_date(
                   to_utc_timestamp(CAST(CAST(epoch as BIGINT) / 1000 AS TIMESTAMP), 'PST'))
           ELSE to_date(to_utc_timestamp(CAST(CAST(epoch as BIGINT) AS TIMESTAMP), 'PST')) END dt_utc,
       `DATE`                                                                                  dt,
       `DATE`,
       event_time,
       epoch,
       event_name,
       user_id,
       source_url,
       sid,
       said,
       keyword,
       adgroup_id,
       action_worth,
       ip,
       ua,
       referrer_domain,
       ads_returned,
       country_name,
       country_iso_code,
       click_id,
       data_source,
       external_referrer,
       push_user_id,
       impression_id,
       keyword_rank,
       ad_unit_name,
       event_uuid,
       NULL                                                                                    dst_url,
       NULL                                                                                    error_message,
       NULL                                                                                    js_version,
       NULL                                                                                    ext_version,
       NULL                                                                                    ad_unit_updated_type,
       NULL                                                                                    ad_unit_updated_by,
       NULL                                                                                    ad_unit_old_version,
       NULL                                                                                    ad_unit_new_version,
       partition_time,
       NULL                                                                                    ad_unit_version,
       NULL                                                                                    affiliate_id,
       NULL                                                                                    display_url,
       NULL                                                                                    pre_event_uuid,
       NULL                                                                                    receivetimestamp,
       NULL                                                                                    sub_affiliate_id,
       NULL                                                                                    uuid
FROM addotnet.raw_user_events_history
WHERE dt < '2020-05-07'
UNION ALL
SELECT CASE
           WHEN length(CAST(epoch as STRING)) = 13 THEN to_date(
                   to_utc_timestamp(CAST(CAST(epoch as BIGINT) / 1000 AS TIMESTAMP), 'PST'))
           ELSE to_date(to_utc_timestamp(CAST(CAST(epoch as BIGINT) AS TIMESTAMP), 'PST')) END dt_utc,
       `DATE`                                                                                  dt,
       `DATE`,
       event_time,
       epoch,
       event_name,
       user_id,
       source_url,
       sid,
       said,
       keyword,
       adgroup_id,
       action_worth,
       ip,
       ua,
       referrer_domain,
       ads_returned,
       country_name,
       NULL                                                                                    country_iso_code,
       click_id,
       data_source,
       external_referrer,
       push_user_id,
       impression_id,
       keyword_rank,
       ad_unit_name,
       event_uuid,
       dst_url,
       error_message,
       js_version,
       ext_version,
       ad_unit_updated_type,
       ad_unit_updated_by,
       ad_unit_old_version,
       ad_unit_new_version,
       partition_time,
       NULL                                                                                    ad_unit_version,
       NULL                                                                                    affiliate_id,
       NULL                                                                                    display_url,
       NULL                                                                                    pre_event_uuid,
       NULL                                                                                    receivetimestamp,
       NULL                                                                                    sub_affiliate_id,
       NULL                                                                                    uuid
FROM addotnet.raw_user_event_history1
WHERE dt >= '2020-05-07'
  AND dt <= '2020-11-17'
UNION ALL
SELECT to_date(dt)                dt_utc,
       `DATE`                     dt,
       `DATE`,
       event_time,
       unix_timestamp(event_time) epoch,
       event_name,
       user_id,
       source_url,
       sid,
       said,
       keyword,
       adgroup_id,
       action_worth.member1       action_worth,
       ip,
       ua,
       referrer_domain,
       ads_returned.member1       ads_returned,
       country_name,
       NULL                       country_iso_code,
       click_id,
       data_source,
       external_referrer,
       push_user_id,
       impression_id,
       keyword_rank.member1       keyword_rank,
       ad_unit_name,
       event_uuid,
       dst_url,
       error_message,
       js_version,
       ext_version,
       ad_unit_updated_type,
       ad_unit_updated_by,
       ad_unit_old_version,
       ad_unit_new_version,
       partition_time,
       ad_unit_version,
       affiliate_id,
       display_url,
       pre_event_uuid,
       receivetimestamp,
       sub_affiliate_id,
       uuid
FROM addotnet.raw_user_events_live
WHERE dt >= '2020-11-18';


drop table if exists backfill.raw_user_events_new_tmp2;
CREATE TABLE backfill.raw_user_events_new_tmp2
(
    dt_utc               string,
    `date`               string,
    event_time           string,
    epoch                bigint,
    event_name           string,
    user_id              string,
    source_url           string,
    sid                  string,
    said                 string,
    keyword              string,
    adgroup_id           string,
    action_worth         double,
    ip                   string,
    ua                   string,
    referrer_domain      string,
    ads_returned         double,
    country_name         string,
    country_iso_code     string,
    click_id             string,
    data_source          string,
    external_referrer    string,
    push_user_id         string,
    impression_id        string,
    keyword_rank         double,
    ad_unit_name         string,
    event_uuid           string,
    dst_url              string,
    error_message        string,
    js_version           string,
    ext_version          string,
    ad_unit_updated_type string,
    ad_unit_updated_by   string,
    ad_unit_old_version  string,
    ad_unit_new_version  string,
    partition_time       bigint,
    ad_unit_version      string,
    affiliate_id         string,
    display_url          string,
    pre_event_uuid       string,
    receivetimestamp     bigint,
    sub_affiliate_id     string,
    uuid                 string,
    dt_val               STRING
) PARTITIONED BY (   dt STRING )
STORED AS PARQUET LOCATION 'hdfs://nn1.data.int.dc1.ad.net:8020/user/hive/warehouse/backfill.db/raw_user_events_new_tmp2';


INSERT OVERWRITE backfill.raw_user_events_new_tmp2 (dt_utc,
                                                    dt,
                                                    `date`,
                                                    event_time,
                                                    epoch,
                                                    event_name,
                                                    user_id,
                                                    source_url,
                                                    sid,
                                                    said,
                                                    keyword,
                                                    adgroup_id,
                                                    action_worth,
                                                    ip,
                                                    ua,
                                                    referrer_domain,
                                                    ads_returned,
                                                    country_name,
                                                    country_iso_code,
                                                    click_id,
                                                    data_source,
                                                    external_referrer,
                                                    push_user_id,
                                                    impression_id,
                                                    keyword_rank,
                                                    ad_unit_name,
                                                    event_uuid,
                                                    dst_url,
                                                    error_message,
                                                    js_version,
                                                    ext_version,
                                                    ad_unit_updated_type,
                                                    ad_unit_updated_by,
                                                    ad_unit_old_version,
                                                    ad_unit_new_version,
                                                    partition_time,
                                                    ad_unit_version,
                                                    affiliate_id,
                                                    display_url,
                                                    pre_event_uuid,
                                                    receivetimestamp,
                                                    sub_affiliate_id,
                                                    uuid, dt_val)
select dt_utc,
       dt,
       `date`,
       event_time,
       epoch,
       event_name,
       user_id,
       source_url,
       sid,
       said,
       keyword,
       adgroup_id,
       action_worth,
       ip,
       ua,
       referrer_domain,
       ads_returned,
       country_name,
       country_iso_code,
       click_id,
       data_source,
       external_referrer,
       push_user_id,
       impression_id,
       keyword_rank,
       ad_unit_name,
       event_uuid,
       dst_url,
       error_message,
       js_version,
       ext_version,
       ad_unit_updated_type,
       ad_unit_updated_by,
       ad_unit_old_version,
       ad_unit_new_version,
       partition_time,
       ad_unit_version,
       affiliate_id,
       display_url,
       pre_event_uuid,
       receivetimestamp,
       sub_affiliate_id,
       uuid,
       dt as dt_val
FROM addotnet.raw_user_events_new
where dt > '2021-01-01';



alter table addotnet.raw_user_events
    drop partition ('2020-10-20');
alter table addotnet.raw_user_events
    drop partition ('2020-10-21');
alter table addotnet.raw_user_events
    drop partition ('2020-10-22');
alter table addotnet.raw_user_events
    drop partition ('2020-10-23');
alter table addotnet.raw_user_events
    drop partition ('2020-10-24');
alter table addotnet.raw_user_events
    drop partition ('2020-10-25');
alter table addotnet.raw_user_events
    drop partition ('2020-10-26');
alter table addotnet.raw_user_events
    drop partition ('2020-10-27');
alter table addotnet.raw_user_events
    drop partition ('2020-10-28');
alter table addotnet.raw_user_events
    drop partition ('2020-10-29');


alter table addotnet.raw_user_events
    drop partition ('2021-05-02');

DROP TABLE IF EXISTS test.raw_user_events_live_hdfs_parquet;
CREATE TABLE test.raw_user_events_live_hdfs_parquet
(
    dt_utc               Nullable(String),
    `date`               Nullable(String),
    event_time           Nullable(String),
    epoch                Nullable(BIGINT),
    event_name           Nullable(String),
    user_id              Nullable(String),
    source_url           Nullable(String),
    sid                  Nullable(String),
    said                 Nullable(String),
    keyword              Nullable(String),
    adgroup_id           Nullable(String),
    action_worth         Nullable(DOUBLE),
    ip                   Nullable(String),
    ua                   Nullable(String),
    referrer_domain      Nullable(String),
    ads_returned         Nullable(DOUBLE),
    country_name         Nullable(String),
    country_iso_code     Nullable(String),
    click_id             Nullable(String),
    data_source          Nullable(String),
    external_referrer    Nullable(String),
    push_user_id         Nullable(String),
    impression_id        Nullable(String),
    keyword_rank         Nullable(DOUBLE),
    ad_unit_name         Nullable(String),
    event_uuid           Nullable(String),
    dst_url              Nullable(String),
    error_message        Nullable(String),
    js_version           Nullable(String),
    ext_version          Nullable(String),
    ad_unit_updated_type Nullable(String),
    ad_unit_updated_by   Nullable(String),
    ad_unit_old_version  Nullable(String),
    ad_unit_new_version  Nullable(String),
    partition_time       Nullable(BIGINT),
    ad_unit_version      Nullable(String),
    affiliate_id         Nullable(String),
    display_url          Nullable(String),
    pre_event_uuid       Nullable(String),
    receivetimestamp     Nullable(BIGINT),
    sub_affiliate_id     Nullable(String),
    uuid                 Nullable(String),
    dt_val               Nullable(String)
) ENGINE = HDFS(
           'hdfs://nn1.data.int.dc1.ad.net:8020/user/hive/warehouse/backfill.db/raw_user_events_new_tmp2/dt=2020-05-02/*',
           'Parquet');


insert into addotnet.raw_user_events (kafka_dt, dt_utc, dt,
                                      date,
                                      event_time,
                                      epoch,
                                      event_name,
                                      user_id,
                                      source_url,
                                      sid,
                                      said,
                                      keyword,
                                      adgroup_id,
                                      action_worth,
                                      ip,
                                      ua,
                                      referrer_domain,
                                      ads_returned,
                                      country_name,
                                      country_iso_code,
                                      click_id,
                                      data_source,
                                      external_referrer,
                                      push_user_id,
                                      impression_id,
                                      keyword_rank,
                                      ad_unit_name,
                                      event_uuid,
                                      dst_url,
                                      error_message,
                                      js_version,
                                      ext_version,
                                      ad_unit_updated_type,
                                      ad_unit_updated_by,
                                      ad_unit_old_version,
                                      ad_unit_new_version,
                                      partition_time,
                                      ad_unit_version,
                                      affiliate_id,
                                      display_url,
                                      pre_event_uuid,
                                      receivetimestamp,
                                      sub_affiliate_id,
                                      uuid)
select dt_val,
       dt_utc,
       dt_val as dt,
       date,
       event_time,
       epoch,
       event_name,
       user_id,
       source_url,
       coalesce(sid, ''),
       coalesce(said, ''),
       keyword,
       adgroup_id,
       action_worth,
       ip,
       ua,
       referrer_domain,
       ads_returned,
       country_name,
       country_iso_code,
       click_id,
       data_source,
       external_referrer,
       push_user_id,
       impression_id,
       keyword_rank,
       ad_unit_name,
       event_uuid,
       dst_url,
       error_message,
       js_version,
       ext_version,
       ad_unit_updated_type,
       ad_unit_updated_by,
       ad_unit_old_version,
       ad_unit_new_version,
       partition_time,
       ad_unit_version,
       affiliate_id,
       display_url,
       pre_event_uuid,
       receivetimestamp,
       sub_affiliate_id,
       uuid
from test.raw_user_events_live_hdfs_parquet;