ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',0, 'request');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',1 ,'request');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',2 ,'request');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',3 ,'request');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',4 ,'request');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',5 ,'request');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',6 ,'request');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',7 ,'request');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',8 ,'request');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',9 ,'request');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',10,'request');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',11,'request');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',12,'request');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',13,'request');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',14,'request');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',15,'request');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',16,'request');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',17,'request');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',18,'request');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',19,'request');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',20,'request');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',21,'request');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',22,'request');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',23,'request');

ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',0, 'ad_return');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',1 ,'ad_return');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',2 ,'ad_return');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',3 ,'ad_return');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',4 ,'ad_return');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',5 ,'ad_return');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',6 ,'ad_return');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',7 ,'ad_return');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',8 ,'ad_return');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',9 ,'ad_return');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',10,'ad_return');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',11,'ad_return');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',12,'ad_return');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',13,'ad_return');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',14,'ad_return');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',15,'ad_return');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',16,'ad_return');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',17,'ad_return');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',18,'ad_return');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',19,'ad_return');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',20,'ad_return');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',21,'ad_return');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',22,'ad_return');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',23,'ad_return');

ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',0, 'click');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',1 ,'click');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',2 ,'click');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',3 ,'click');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',4 ,'click');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',5 ,'click');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',6 ,'click');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',7 ,'click');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',8 ,'click');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',9 ,'click');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',10,'click');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',11,'click');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',12,'click');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',13,'click');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',14,'click');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',15,'click');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',16,'click');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',17,'click');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',18,'click');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',19,'click');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',20,'click');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',21,'click');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',22,'click');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',23,'click');

ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',0, 'action');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',1 ,'action');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',2 ,'action');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',3 ,'action');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',4 ,'action');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',5 ,'action');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',6 ,'action');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',7 ,'action');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',8 ,'action');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',9 ,'action');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',10,'action');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',11,'action');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',12,'action');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',13,'action');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',14,'action');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',15,'action');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',16,'action');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',17,'action');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',18,'action');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',19,'action');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',20,'action');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',21,'action');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',22,'action');
ALTER TABLE addotnet.ad_event DROP PARTITION ('PROCESS_DATE',23,'action');

select count(*) from addotnet.ad_event where dt = 'PROCESS_DATE';